# Generated by Django 4.2.13 on 2024-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0002_experience_alter_user_about_alter_user_avatar_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.ImageField(blank=True, upload_to='social_images/'),
        ),
    ]
